# Generated by Django 5.0.3 on 2024-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_login_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
